"""Inference artifact generation (spec §18, §19, §20).

Writes the files that let someone take ``model_package.zip`` to a machine that has never
seen this project:

* ``inference/model_loader.py`` - loads preprocessor, model and schema **in the correct
  order** and exposes ``load_model(path).predict(data)``. It imports nothing from
  ``rl_automl``; that is the whole point of the package.
* ``inference/predict.py`` - a runnable demonstration, also dependency-free.
* ``requirements.txt`` - inference dependencies only, not the training environment.
* ``README.md`` - model, task, expected input schema, install, usage, example I/O, metrics.
* ``inference/example_input.csv`` - a schema-shaped example.

The example input is **synthesised from the schema**, not sampled from the user's data, so
the package never carries user rows out of the system (spec §17).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import Any

import pandas as pd

from rl_automl.core.config import AutoMLConfig
from rl_automl.core.errors import PackagingError
from rl_automl.core.logging import get_logger
from rl_automl.packaging.model_exporter import FeatureSchema, ModelPackage
from rl_automl.packaging.runtime_bundle import runtime_module_map

logger = get_logger("packaging.inference_generator")

MODEL_LOADER_TEMPLATE = '''"""Model loader for this package.

Generated by RL-AutoML. Self-contained by design: it depends only on
numpy, pandas, joblib and the library that trained the model -- never on the
AutoML package itself.

Usage:
    from model_loader import load_model

    model = load_model("model_package")
    predictions = model.predict(new_data)
"""

from __future__ import annotations

import importlib.util
import json
import sys
import types
import warnings
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd

SCHEMA_FILE = "metadata/feature_schema.json"
MODEL_METADATA_FILE = "metadata/model_metadata.json"
DATASET_METADATA_FILE = "metadata/dataset_metadata.json"
MODEL_FILE = "model/$MODEL_FILENAME"
PREPROCESSOR_FILE = "preprocessing/preprocessor.joblib"

# Pickled estimators record the dotted path of the class that defined them. These are the
# modules that define such classes, shipped inside the package under `runtime/`.
RUNTIME_MODULES = $RUNTIME_MODULES


def _install_runtime_modules(root: Path) -> list[str]:
    """Make this package's own copies of its classes importable, without AutoML installed.

    The `rl_automl` namespaces are registered as placeholder parents, then each shipped
    source file is executed under its original dotted name, so unpickling finds exactly the
    class it recorded.
    """
    installed: list[str] = []
    for module_name, relative in RUNTIME_MODULES.items():
        if module_name in sys.modules:
            continue
        path = root / relative
        if not path.is_file():
            continue

        parts = module_name.split(".")
        for depth in range(1, len(parts)):
            parent = ".".join(parts[:depth])
            if parent not in sys.modules:
                sys.modules[parent] = types.ModuleType(parent)

        spec = importlib.util.spec_from_file_location(module_name, path)
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        try:
            spec.loader.exec_module(module)
        except Exception:
            sys.modules.pop(module_name, None)
            continue

        owner, _, attribute = module_name.rpartition(".")
        if owner and owner in sys.modules:
            setattr(sys.modules[owner], attribute, module)
        installed.append(module_name)
    return installed


class SchemaMismatchError(ValueError):
    """The supplied data does not match the schema this model was trained on."""


class LoadedModel:
    """A fitted preprocessor plus a fitted model, loaded in the correct order."""

    def __init__(
        self,
        model: Any,
        preprocessor: Any,
        schema: dict[str, Any],
        model_metadata: dict[str, Any],
        dataset_metadata: dict[str, Any],
        package_dir: Path,
    ) -> None:
        self.model = model
        self.preprocessor = preprocessor
        self.schema = schema
        self.model_metadata = model_metadata
        self.dataset_metadata = dataset_metadata
        self.package_dir = Path(package_dir)

        self.feature_names = [feature["name"] for feature in schema.get("features", [])]
        self.datetime_features = [
            feature["name"]
            for feature in schema.get("features", [])
            if feature.get("kind") == "datetime"
        ]
        self.numeric_features = [
            feature["name"]
            for feature in schema.get("features", [])
            if feature.get("kind") == "numeric"
        ]
        self.label_mapping = model_metadata.get("label_mapping") or None
        self.task_type = model_metadata.get("task", schema.get("task_type", ""))

    # -- public API ---------------------------------------------------------------

    def predict(self, data: Any) -> np.ndarray:
        """Predict labels (classification) or values (regression).

        `data` may be a DataFrame, a dict of columns, a list of row dicts, or a path to a
        CSV/Parquet file.
        """
        frame = self.prepare(data)
        transformed = np.asarray(self.preprocessor.transform(frame), dtype=np.float64)
        raw = np.asarray(self.model.predict(transformed))
        return self._decode(raw)

    def predict_proba(self, data: Any) -> np.ndarray | None:
        """Class probabilities where the model provides them, else None."""
        if not hasattr(self.model, "predict_proba"):
            return None
        frame = self.prepare(data)
        transformed = np.asarray(self.preprocessor.transform(frame), dtype=np.float64)
        return np.asarray(self.model.predict_proba(transformed))

    def prepare(self, data: Any) -> pd.DataFrame:
        """Validate and coerce input into exactly the frame the preprocessor expects."""
        frame = self._to_frame(data)
        self._check_columns(frame)

        for name in self.datetime_features:
            if name in frame.columns:
                frame[name] = pd.to_datetime(frame[name], errors="coerce", format="mixed")
        for name in self.numeric_features:
            if name in frame.columns:
                frame[name] = pd.to_numeric(frame[name], errors="coerce")

        # Column order is normalised so results do not depend on how the caller built the frame.
        return frame[self.feature_names]

    # -- internals ----------------------------------------------------------------

    @staticmethod
    def _to_frame(data: Any) -> pd.DataFrame:
        if isinstance(data, pd.DataFrame):
            return data.copy()
        if isinstance(data, (str, Path)):
            path = Path(data)
            if not path.is_file():
                raise FileNotFoundError(f"input file not found: {path}")
            if path.suffix.lower() == ".parquet":
                return pd.read_parquet(path)
            return pd.read_csv(path)
        if isinstance(data, dict):
            return pd.DataFrame(data)
        if isinstance(data, list):
            return pd.DataFrame(data)
        raise TypeError(
            "unsupported input type; pass a DataFrame, dict, list of rows, or a CSV path"
        )

    def _check_columns(self, frame: pd.DataFrame) -> None:
        missing = [name for name in self.feature_names if name not in frame.columns]
        if missing:
            raise SchemaMismatchError(
                "input is missing "
                + str(len(missing))
                + " required column(s): "
                + ", ".join(missing[:10])
                + ("..." if len(missing) > 10 else "")
            )
        extra = [column for column in frame.columns if column not in set(self.feature_names)]
        if extra:
            warnings.warn(
                "ignoring "
                + str(len(extra))
                + " unexpected column(s): "
                + ", ".join(map(str, extra[:10])),
                stacklevel=2,
            )

    def _decode(self, raw: np.ndarray) -> np.ndarray:
        """Map encoded class indices back to the original labels."""
        if not self.label_mapping:
            return raw
        try:
            indices = raw.astype(int)
        except (TypeError, ValueError):
            return raw
        labels = np.array([self.label_mapping[str(index)] for index in indices], dtype=object)
        return labels

    def describe(self) -> dict[str, Any]:
        return {
            "model": self.model_metadata.get("model"),
            "task": self.task_type,
            "primary_metric": self.model_metadata.get("primary_metric"),
            "validation_score": self.model_metadata.get("validation_score"),
            "test_score": self.model_metadata.get("test_score"),
            "n_features": len(self.feature_names),
            "classes": self.schema.get("output", {}).get("classes"),
        }


def load_model(package_dir: str | Path = "model_package") -> LoadedModel:
    """Load a packaged model. This is the documented entry point."""
    root = Path(package_dir)
    if not root.is_dir():
        raise FileNotFoundError(f"package directory not found: {root}")

    def read(relative: str) -> dict[str, Any]:
        path = root / relative
        if not path.is_file():
            raise FileNotFoundError(f"package is incomplete; missing {relative}")
        return json.loads(path.read_text(encoding="utf-8"))

    schema = read(SCHEMA_FILE)
    model_metadata = read(MODEL_METADATA_FILE)
    dataset_metadata = read(DATASET_METADATA_FILE)

    preprocessor_path = root / PREPROCESSOR_FILE
    model_path = root / MODEL_FILE
    if not preprocessor_path.is_file():
        raise FileNotFoundError(f"package is incomplete; missing {PREPROCESSOR_FILE}")
    if not model_path.is_file():
        raise FileNotFoundError(f"package is incomplete; missing {MODEL_FILE}")

    # Before unpickling: the artifact's classes must resolve without the AutoML package.
    _install_runtime_modules(root)

    preprocessor = joblib.load(preprocessor_path)
    model = joblib.load(model_path)

    # Some estimators carry an explicit device; inference is always CPU.
    if hasattr(model, "to_cpu"):
        model.to_cpu()

    return LoadedModel(model, preprocessor, schema, model_metadata, dataset_metadata, root)


__all__ = ["load_model", "LoadedModel", "SchemaMismatchError"]
'''

PREDICT_TEMPLATE = '''"""Runnable inference demo for this model package.

    python predict.py
    python predict.py --input my_rows.csv

Generated by RL-AutoML. Depends only on model_loader and the model's own library.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from model_loader import load_model

HERE = Path(__file__).resolve().parent
PACKAGE_DIR = HERE.parent if (HERE.parent / "metadata").is_dir() else HERE
EXAMPLE_INPUT = HERE / "example_input.csv"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run inference with this packaged model.")
    parser.add_argument(
        "--input",
        default=str(EXAMPLE_INPUT),
        help="CSV/Parquet file with one row per prediction (defaults to example_input.csv)",
    )
    arguments = parser.parse_args()

    model = load_model(PACKAGE_DIR)
    description = model.describe()

    print("Model        :", description["model"])
    print("Task         :", description["task"])
    print("Metric       :", description["primary_metric"])
    print("Validation   :", description["validation_score"])
    print("Test         :", description["test_score"])
    print("Features     :", description["n_features"])
    if description["classes"]:
        print("Classes      :", ", ".join(description["classes"]))
    print()

    print("Input        :", arguments.input)
    predictions = model.predict(arguments.input)
    print("Predictions  :", list(predictions)[:20])

    probabilities = model.predict_proba(arguments.input)
    if probabilities is not None:
        print("Probabilities:", probabilities[:5].round(4).tolist())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

README_TEMPLATE = """# $MODEL_DISPLAY_NAME model package

Deployment-ready artifact produced by RL-AutoML.

## Model

| Field | Value |
| --- | --- |
| Model | $MODEL_DISPLAY_NAME (`$MODEL_KEY`) |
| Framework | $FRAMEWORK |
| Task | $TASK_TYPE |
| Objective | $OBJECTIVE |
| Primary metric | $PRIMARY_METRIC ($METRIC_DIRECTION) |
| Validation score | $VALIDATION_SCORE |
| Test score | $TEST_SCORE |
| Raw features | $RAW_FEATURES |
| Transformed features | $TRANSFORMED_FEATURES |
| Training time | $TRAINING_TIME s |
| Peak memory | $PEAK_MEMORY MB |
| Trained at | $TRAINING_TIMESTAMP |
| Run id | $RUN_ID |

$DOWNLOAD_NOTE

## Installation

```
pip install -r requirements.txt
```

## Expected input

One row per prediction. Required columns:

$FEATURE_TABLE

$TARGET_NOTE

## Usage

```python
from model_loader import load_model

model = load_model("model_package")

# A DataFrame, a dict, a list of row dicts, or a path to a CSV/Parquet file
predictions = model.predict("new_rows.csv")
print(predictions)
```

From the command line:

```
python predict.py --input new_rows.csv
```

## Example

Input (`inference/example_input.csv`, synthesised from the schema -- it contains no real data):

```
$EXAMPLE_INPUT
```

Output:

```
$EXAMPLE_OUTPUT
```

## Preprocessing

The package includes the **fitted** preprocessor, so the transformations applied here are
exactly the ones used at training time. In order:

$PREPROCESSING_LIST

Nothing needs to be re-fitted before use. Unseen categories in categorical columns are
routed to the encoder's infrequent bucket rather than raising.

## Metrics

$METRICS_BLOCK

## Training data

| Field | Value |
| --- | --- |
| Dataset | $DATASET_NAME |
| SHA-256 | $DATASET_SHA |
| Rows | $DATASET_ROWS |
| Columns | $DATASET_COLS |
| Missing ratio | $DATASET_MISSING |
| Split | $SPLIT_DESCRIPTION |

$WARNINGS_BLOCK

## Contents

```
$CONTENTS
```

## Notes

* `predict()` returns the original label names, not encoded integers.
* `predict_proba()` returns class probabilities for classifiers that support it, else `None`.
* Inference runs on CPU only.
$ONNX_NOTE
"""

REQUIREMENTS_TEMPLATE = """$REQUIREMENTS
# Model-specific dependency
$FRAMEWORK_REQUIREMENT
"""


@dataclass
class GeneratedInference:
    files: list[Path]
    example_input: pd.DataFrame | None = None
    requirements: list[str] | None = None


class InferenceGenerator:
    def __init__(self, config: AutoMLConfig | None = None) -> None:
        self.config = config or AutoMLConfig()

    def generate(
        self,
        package: ModelPackage,
        *,
        split_summary: dict[str, Any] | None = None,
        include_readme: bool | None = None,
    ) -> GeneratedInference:
        """Write every inference-side file into an already-exported package directory."""
        directory = package.directory
        inference_dir = directory / "inference"
        inference_dir.mkdir(parents=True, exist_ok=True)

        written: list[Path] = []

        loader = MODEL_LOADER_TEMPLATE.replace("$MODEL_FILENAME", "model.joblib").replace(
            "$RUNTIME_MODULES", json.dumps(runtime_module_map(), indent=4)
        )
        written.append(self._write(inference_dir / "model_loader.py", loader))
        written.append(self._write(inference_dir / "predict.py", PREDICT_TEMPLATE))

        example = self._example_frame(package.schema)
        if example is not None:
            example_path = inference_dir / "example_input.csv"
            example.to_csv(example_path, index=False)
            written.append(example_path)

        requirements = self._requirements(package)
        written.append(
            self._write(
                directory / "requirements.txt",
                REQUIREMENTS_TEMPLATE.replace(
                    "$REQUIREMENTS", "\n".join(requirements[:-1])
                ).replace("$FRAMEWORK_REQUIREMENT", requirements[-1]),
            )
        )

        should_write_readme = (
            self.config.packaging.include_readme if include_readme is None else include_readme
        )
        if should_write_readme:
            written.append(
                self._write(
                    directory / "README.md",
                    self._readme(package, example, split_summary or {}),
                )
            )

        return GeneratedInference(files=written, example_input=example, requirements=requirements)

    # -- pieces ------------------------------------------------------------------

    def _requirements(self, package: ModelPackage) -> list[str]:
        """Inference dependencies only. The training environment is not shipped."""
        base = list(self.config.packaging.inference_requirements)
        framework = str(package.metadata.get("framework", "scikit-learn"))
        framework_line = {
            "xgboost": "xgboost>=2.0",
            "lightgbm": "lightgbm>=4.0",
            "torch": "torch>=2.2",
        }.get(framework, "scikit-learn>=1.4")
        if framework == "scikit-learn" and any(line.startswith("scikit-learn") for line in base):
            return base
        return [*base, framework_line]

    def _example_frame(self, schema: FeatureSchema) -> pd.DataFrame | None:
        """A single schema-shaped row using safe placeholder values.

        Synthesised on purpose: shipping real rows would leak user data into a downloadable
        artifact.
        """
        if not schema.features:
            return None

        row: dict[str, Any] = {}
        for feature in schema.features:
            if feature.kind == "numeric":
                row[feature.name] = 0.0
            elif feature.kind == "datetime":
                row[feature.name] = "2024-01-01"
            elif feature.example_values:
                row[feature.name] = feature.example_values[0]
            else:
                row[feature.name] = "value"
        return pd.DataFrame([row])

    def _readme(
        self,
        package: ModelPackage,
        example: pd.DataFrame | None,
        split_summary: dict[str, Any],
    ) -> str:
        metadata = package.metadata
        schema = package.schema
        dataset = metadata.get("dataset", {})
        dataset_metadata = {}
        dataset_metadata_path = package.directory / "metadata" / "dataset_metadata.json"
        if dataset_metadata_path.is_file():
            import json

            dataset_metadata = json.loads(dataset_metadata_path.read_text(encoding="utf-8"))

        feature_rows = "\n".join(
            f"| `{feature.name}` | {feature.kind} | {'yes' if feature.required else 'no'} | "
            f"{'yes' if feature.nullable else 'no'} | {feature.n_unique or ''} |"
            for feature in schema.features
        )
        feature_table = (
            "| Column | Kind | Required | Nullable | Unique values |\n"
            "| --- | --- | --- | --- | --- |\n" + feature_rows
            if feature_rows
            else "_No input columns were recorded._"
        )

        metrics_block = self._metrics_block(metadata)
        example_input = example.to_csv(index=False).strip() if example is not None else "n/a"
        example_output = self._example_output(metadata, schema)

        preprocessing = metadata.get("preprocessing") or []
        preprocessing_list = (
            "\n".join(f"{index + 1}. `{name}`" for index, name in enumerate(preprocessing))
            if preprocessing
            else "_None beyond the schema coercion performed by the loader._"
        )

        warnings = list(metadata.get("warnings", [])) + list(dataset_metadata.get("warnings", []))
        warnings_block = (
            "## Recorded warnings\n\n" + "\n".join(f"* {warning}" for warning in warnings)
            if warnings
            else ""
        )

        contents = "\n".join(
            str(path.relative_to(package.directory)).replace("\\", "/") for path in package.files()
        )

        target_note = (
            f"`{schema.target}` is the training target and is **not** an input column."
            if schema.target
            else "This is an unsupervised model; no target column was used."
        )

        onnx_note = (
            "\n* An ONNX export is included at `model/model.onnx`; it was verified to match "
            "the native model on a probe sample.\n"
            if package.has_onnx()
            else ""
        )

        download_note = (
            "This package was verified after being archived: the ZIP was re-opened, its "
            "checksums tested, and its model reloaded and compared against the in-process "
            "model."
        )

        return Template(README_TEMPLATE).safe_substitute(
            MODEL_DISPLAY_NAME=metadata.get("model", "Unknown"),
            MODEL_KEY=metadata.get("model_key", ""),
            FRAMEWORK=metadata.get("framework", ""),
            TASK_TYPE=metadata.get("task", ""),
            OBJECTIVE=metadata.get("objective", ""),
            PRIMARY_METRIC=metadata.get("primary_metric", ""),
            METRIC_DIRECTION=metadata.get("metric_direction", ""),
            VALIDATION_SCORE=_format_number(metadata.get("validation_score")),
            TEST_SCORE=_format_number(metadata.get("test_score")),
            RAW_FEATURES=str(metadata.get("raw_features", "")),
            TRANSFORMED_FEATURES=str(metadata.get("features", "")),
            TRAINING_TIME=_format_number(metadata.get("resource_usage", {}).get("training_time_s")),
            PEAK_MEMORY=_format_number(metadata.get("resource_usage", {}).get("peak_memory_mb")),
            TRAINING_TIMESTAMP=metadata.get("training_timestamp", ""),
            RUN_ID=metadata.get("run_id", ""),
            DOWNLOAD_NOTE=download_note,
            FEATURE_TABLE=feature_table,
            TARGET_NOTE=target_note,
            EXAMPLE_INPUT=example_input,
            EXAMPLE_OUTPUT=example_output,
            PREPROCESSING_LIST=preprocessing_list,
            METRICS_BLOCK=metrics_block,
            DATASET_NAME=dataset.get("name", ""),
            DATASET_SHA=dataset.get("sha256", ""),
            DATASET_ROWS=str(dataset_metadata.get("n_rows", "")),
            DATASET_COLS=str(dataset_metadata.get("n_cols", "")),
            DATASET_MISSING=_format_number(dataset_metadata.get("missing_ratio")),
            SPLIT_DESCRIPTION=_split_description(split_summary),
            WARNINGS_BLOCK=warnings_block,
            CONTENTS=contents,
            ONNX_NOTE=onnx_note,
        )

    @staticmethod
    def _metrics_block(metadata: dict[str, Any]) -> str:
        validation = metadata.get("validation_metrics") or {}
        test = metadata.get("test_metrics") or {}
        names = sorted(set(validation) | set(test))
        if not names:
            return "_No metrics were recorded._"
        rows = "\n".join(
            f"| {name} | {_format_number(validation.get(name))} "
            f"| {_format_number(test.get(name))} |"
            for name in names
        )
        return "| Metric | Validation | Test |\n| --- | --- | --- |\n" + rows

    @staticmethod
    def _example_output(metadata: dict[str, Any], schema: FeatureSchema) -> str:
        classes = schema.output.get("classes") or []
        if metadata.get("task") == "classification" and classes:
            return classes[-1]
        if metadata.get("task") == "regression":
            return "123.45"
        return "<prediction>"

    @staticmethod
    def _write(path: Path, content: str) -> Path:
        try:
            path.write_text(content, encoding="utf-8")
        except OSError as exc:  # pragma: no cover - disk issues
            raise PackagingError(f"could not write {path}: {exc}") from exc
        return path


def _format_number(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, int | float):
        return f"{value:.4f}".rstrip("0").rstrip(".") if isinstance(value, float) else str(value)
    return str(value)


def _split_description(split_summary: dict[str, Any]) -> str:
    if not split_summary:
        return ""
    return (
        f"{split_summary.get('strategy', '')} - "
        f"train {split_summary.get('n_train', '?')}, "
        f"validation {split_summary.get('n_val', '?')}, "
        f"test {split_summary.get('n_test', '?')}"
    )


__all__ = ["GeneratedInference", "InferenceGenerator"]
