"""Model loader for this package.

Generated by RL-AutoML. Self-contained by design: it depends only on
numpy, pandas, joblib and the library that trained the model -- never on the
AutoML package itself.

Usage:
    from model_loader import load_model

    model = load_model("model_package")
    predictions = model.predict(new_data)
"""

from __future__ import annotations

import importlib.util
import json
import sys
import types
import warnings
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd

SCHEMA_FILE = "metadata/feature_schema.json"
MODEL_METADATA_FILE = "metadata/model_metadata.json"
DATASET_METADATA_FILE = "metadata/dataset_metadata.json"
MODEL_FILE = "model/model.joblib"
PREPROCESSOR_FILE = "preprocessing/preprocessor.joblib"

# Pickled estimators record the dotted path of the class that defined them. These are the
# modules that define such classes, shipped inside the package under `runtime/`.
RUNTIME_MODULES = {
    "rl_automl.execution.runtime_transformers": "runtime/execution/runtime_transformers.py",
    "rl_automl.execution.torch_models": "runtime/execution/torch_models.py",
    "rl_automl.core.errors": "runtime/core/errors.py",
    "rl_automl.core.logging": "runtime/core/logging.py"
}


def _install_runtime_modules(root: Path) -> list[str]:
    """Make this package's own copies of its classes importable, without AutoML installed.

    The `rl_automl` namespaces are registered as placeholder parents, then each shipped
    source file is executed under its original dotted name, so unpickling finds exactly the
    class it recorded.
    """
    installed: list[str] = []
    for module_name, relative in RUNTIME_MODULES.items():
        if module_name in sys.modules:
            continue
        path = root / relative
        if not path.is_file():
            continue

        parts = module_name.split(".")
        for depth in range(1, len(parts)):
            parent = ".".join(parts[:depth])
            if parent not in sys.modules:
                sys.modules[parent] = types.ModuleType(parent)

        spec = importlib.util.spec_from_file_location(module_name, path)
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        try:
            spec.loader.exec_module(module)
        except Exception:
            sys.modules.pop(module_name, None)
            continue

        owner, _, attribute = module_name.rpartition(".")
        if owner and owner in sys.modules:
            setattr(sys.modules[owner], attribute, module)
        installed.append(module_name)
    return installed


class SchemaMismatchError(ValueError):
    """The supplied data does not match the schema this model was trained on."""


class LoadedModel:
    """A fitted preprocessor plus a fitted model, loaded in the correct order."""

    def __init__(
        self,
        model: Any,
        preprocessor: Any,
        schema: dict[str, Any],
        model_metadata: dict[str, Any],
        dataset_metadata: dict[str, Any],
        package_dir: Path,
    ) -> None:
        self.model = model
        self.preprocessor = preprocessor
        self.schema = schema
        self.model_metadata = model_metadata
        self.dataset_metadata = dataset_metadata
        self.package_dir = Path(package_dir)

        self.feature_names = [feature["name"] for feature in schema.get("features", [])]
        self.datetime_features = [
            feature["name"]
            for feature in schema.get("features", [])
            if feature.get("kind") == "datetime"
        ]
        self.numeric_features = [
            feature["name"]
            for feature in schema.get("features", [])
            if feature.get("kind") == "numeric"
        ]
        self.label_mapping = model_metadata.get("label_mapping") or None
        self.task_type = model_metadata.get("task", schema.get("task_type", ""))

    # -- public API ---------------------------------------------------------------

    def predict(self, data: Any) -> np.ndarray:
        """Predict labels (classification) or values (regression).

        `data` may be a DataFrame, a dict of columns, a list of row dicts, or a path to a
        CSV/Parquet file.
        """
        frame = self.prepare(data)
        transformed = np.asarray(self.preprocessor.transform(frame), dtype=np.float64)
        raw = np.asarray(self.model.predict(transformed))
        return self._decode(raw)

    def predict_proba(self, data: Any) -> np.ndarray | None:
        """Class probabilities where the model provides them, else None."""
        if not hasattr(self.model, "predict_proba"):
            return None
        frame = self.prepare(data)
        transformed = np.asarray(self.preprocessor.transform(frame), dtype=np.float64)
        return np.asarray(self.model.predict_proba(transformed))

    def prepare(self, data: Any) -> pd.DataFrame:
        """Validate and coerce input into exactly the frame the preprocessor expects."""
        frame = self._to_frame(data)
        self._check_columns(frame)

        for name in self.datetime_features:
            if name in frame.columns:
                frame[name] = pd.to_datetime(frame[name], errors="coerce", format="mixed")
        for name in self.numeric_features:
            if name in frame.columns:
                frame[name] = pd.to_numeric(frame[name], errors="coerce")

        # Column order is normalised so results do not depend on how the caller built the frame.
        return frame[self.feature_names]

    # -- internals ----------------------------------------------------------------

    @staticmethod
    def _to_frame(data: Any) -> pd.DataFrame:
        if isinstance(data, pd.DataFrame):
            return data.copy()
        if isinstance(data, (str, Path)):
            path = Path(data)
            if not path.is_file():
                raise FileNotFoundError(f"input file not found: {path}")
            if path.suffix.lower() == ".parquet":
                return pd.read_parquet(path)
            return pd.read_csv(path)
        if isinstance(data, dict):
            return pd.DataFrame(data)
        if isinstance(data, list):
            return pd.DataFrame(data)
        raise TypeError(
            "unsupported input type; pass a DataFrame, dict, list of rows, or a CSV path"
        )

    def _check_columns(self, frame: pd.DataFrame) -> None:
        missing = [name for name in self.feature_names if name not in frame.columns]
        if missing:
            raise SchemaMismatchError(
                "input is missing "
                + str(len(missing))
                + " required column(s): "
                + ", ".join(missing[:10])
                + ("..." if len(missing) > 10 else "")
            )
        extra = [column for column in frame.columns if column not in set(self.feature_names)]
        if extra:
            warnings.warn(
                "ignoring " + str(len(extra)) + " unexpected column(s): " + ", ".join(map(str, extra[:10])),
                stacklevel=2,
            )

    def _decode(self, raw: np.ndarray) -> np.ndarray:
        """Map encoded class indices back to the original labels."""
        if not self.label_mapping:
            return raw
        try:
            indices = raw.astype(int)
        except (TypeError, ValueError):
            return raw
        labels = np.array([self.label_mapping[str(index)] for index in indices], dtype=object)
        return labels

    def describe(self) -> dict[str, Any]:
        return {
            "model": self.model_metadata.get("model"),
            "task": self.task_type,
            "primary_metric": self.model_metadata.get("primary_metric"),
            "validation_score": self.model_metadata.get("validation_score"),
            "test_score": self.model_metadata.get("test_score"),
            "n_features": len(self.feature_names),
            "classes": self.schema.get("output", {}).get("classes"),
        }


def load_model(package_dir: str | Path = "model_package") -> LoadedModel:
    """Load a packaged model. This is the documented entry point."""
    root = Path(package_dir)
    if not root.is_dir():
        raise FileNotFoundError(f"package directory not found: {root}")

    def read(relative: str) -> dict[str, Any]:
        path = root / relative
        if not path.is_file():
            raise FileNotFoundError(f"package is incomplete; missing {relative}")
        return json.loads(path.read_text(encoding="utf-8"))

    schema = read(SCHEMA_FILE)
    model_metadata = read(MODEL_METADATA_FILE)
    dataset_metadata = read(DATASET_METADATA_FILE)

    preprocessor_path = root / PREPROCESSOR_FILE
    model_path = root / MODEL_FILE
    if not preprocessor_path.is_file():
        raise FileNotFoundError(f"package is incomplete; missing {PREPROCESSOR_FILE}")
    if not model_path.is_file():
        raise FileNotFoundError(f"package is incomplete; missing {MODEL_FILE}")

    # Before unpickling: the artifact's classes must resolve without the AutoML package.
    _install_runtime_modules(root)

    preprocessor = joblib.load(preprocessor_path)
    model = joblib.load(model_path)

    # Some estimators carry an explicit device; inference is always CPU.
    if hasattr(model, "to_cpu"):
        model.to_cpu()

    return LoadedModel(model, preprocessor, schema, model_metadata, dataset_metadata, root)


__all__ = ["load_model", "LoadedModel", "SchemaMismatchError"]
