"""Runnable inference demo for this model package.

    python predict.py
    python predict.py --input my_rows.csv

Generated by RL-AutoML. Depends only on model_loader and the model's own library.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from model_loader import load_model

HERE = Path(__file__).resolve().parent
PACKAGE_DIR = HERE.parent if (HERE.parent / "metadata").is_dir() else HERE
EXAMPLE_INPUT = HERE / "example_input.csv"


def main() -> int:
    parser = argparse.ArgumentParser(description="Run inference with this packaged model.")
    parser.add_argument(
        "--input",
        default=str(EXAMPLE_INPUT),
        help="CSV/Parquet file with one row per prediction (defaults to example_input.csv)",
    )
    arguments = parser.parse_args()

    model = load_model(PACKAGE_DIR)
    description = model.describe()

    print("Model        :", description["model"])
    print("Task         :", description["task"])
    print("Metric       :", description["primary_metric"])
    print("Validation   :", description["validation_score"])
    print("Test         :", description["test_score"])
    print("Features     :", description["n_features"])
    if description["classes"]:
        print("Classes      :", ", ".join(description["classes"]))
    print()

    print("Input        :", arguments.input)
    predictions = model.predict(arguments.input)
    print("Predictions  :", list(predictions)[:20])

    probabilities = model.predict_proba(arguments.input)
    if probabilities is not None:
        print("Probabilities:", probabilities[:5].round(4).tolist())

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
